version: "3.0"
services:
  nfd_frontend:
    build: .
    image: nfd_frontend
    container_name: nfd_frontend
    environment:
      - NODE_ENV=production
    volumes:
      - nfd_frontend_data:/dist
    ports:
      - 6666:8080
    command: ./build.sh

volumes:
  nfd_frontend_data:
    external: true
